### ISSUE TITLE
Does not seem to work on a directory, only individual files

### ISSUE THREAD

**Issue by scottmerker** [ekryski/less2sass#10]
The latest version doesn't seem to process a full directory, only a single file. When processing in a directory it will process the first item, then stop; or will scan and stop.

**Comment by bvandreunen** [comment]
I'm having the same issue. Downgrading to v0.0.2 solves to problem:

`npm install -g less2sass@0.0.2`

**Comment by ekryski** [comment]
My bad gents! Rally dumb typo. It's now fixed in v1.0.2.

**Comment by Igloczek** [comment]
v1.0.3 on Node v10.15 works the same way, just process the first item.
