### ISSUE TITLE
.X float numbers converted like @import X

### ISSUE THREAD

**Issue by carlosbaraza** [ekryski/less2sass#7]
If I try to convert something like:

```
@transition-speed: .3s;
```

it will be converted to:

```
$transition-speed: @import 3s;
```

Thanks for this great tool!

**Comment by mismith** [comment]
+1 also had this issue

**Comment by ekryski** [comment]
Woot! @mismith thanks for the PR. Just checking it now....

**Comment by ekryski** [comment]
Close by #8.
